/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'priority' : Priority,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Priority,
        IDL.Opt(Time),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFilteredTasks' : IDL.Func(
      [IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'updateTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        Priority,
        IDL.Opt(Time),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'priority' : Priority,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Priority,
          IDL.Opt(Time),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFilteredTasks' : IDL.Func(
        [IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'updateTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          Priority,
          IDL.Opt(Time),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };