/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Task {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'tags' : Array<string>,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : string,
  'priority' : Priority,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<
    [string, string, string, Priority, [] | [Time], Array<string>],
    undefined
  >,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTask' : ActorMethod<[string], Task>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFilteredTasks' : ActorMethod<[boolean, [] | [string]], Array<Task>>,
  'listTasks' : ActorMethod<[], Array<Task>>,
  'updateTask' : ActorMethod<
    [string, string, string, boolean, Priority, [] | [Time], Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];